### ISSUE TITLE
Large memory requirement (postprocessing module)

### ISSUE THREAD

**Issue by tschmutzer** [tschmutzer/kmasker#1]
Current version of postprocessing script has large memory footprint. In analyzing occ files Kmasker needs a bug fix to solve this.

**Comment by culpinnis** [comment]
Now it takes one chromosome sequence and one occ sequence at maximum into the memory.
We could by more efficient by working on single bases instead of the whole sequence. 
But I think it is more useful to create a new issue for the realization of this feature in reference to the future development.
