### ISSUE TITLE
Do not hardcode parameter -s for building jellyfish index

### ISSUE THREAD

**Issue by culpinnis** [tschmutzer/kmasker#18]
In kmaskers build routine the parameter -s is hardcoded.

``` perl
system("jellyfish count -m ".$k." -s 24G -t 10 -o KINDEX_".$HASH_info{"short_tag"}."_".$md5sum."_k".$k.".jf ".$seq."");
```

It would be better to make this a parameter which can be configured by the user.
Background: If it is set to a value higher than the systems main memory Jellyfish needs to split up the files and merge them again. This is a really io intensive task and will slow down the process hardly.

**Comment by tschmutzer** [comment]
To solve this an additional parameter ('expert_setting') has been added to Kmasker. It allowes for expert users that own parameters are passed to internal modules of Kmasker.
