### ISSUE TITLE
new implementation of FASTA_Xdivider.pl is incomplete

### ISSUE THREAD

**Issue by tschmutzer** [tschmutzer/kmasker#19]
The new implementation lost position information that can be used to order the final sequences. Need to be integrated again! Otherwise extracted sequences do not have unique identifier!

**Comment by culpinnis** [comment]
Fixed with https://github.com/tschmutzer/kmasker/commit/6fd6c59767161230ea344a3179b0c36e43244251 .
New identifier value was already calculated, but not printed.
