### ISSUE TITLE
Division by zero not captured

### ISSUE THREAD

**Issue by tschmutzer** [tschmutzer/kmasker#20]
In routine 'multi_occ' from module occ.pm the zero case is not propperly handled.

**Comment by culpinnis** [comment]
Yes that is sadly true and my fault. I'll fix it next week.
As far as I can judge the problem for now, it should be resolved by using infinity as the result of the dedicated calculation.
Can you provide a small sample dataset for me to test new implementations?

**Comment by culpinnis** [comment]
Please test commit https://github.com/tschmutzer/kmasker/commit/451643ae9e90f95243f0fccf824abc21e561848c which should handle the issue.
If it is working well, please close this issue.
