### ISSUE TITLE
Implement settings for blast

### ISSUE THREAD

**Issue by culpinnis** [tschmutzer/kmasker#24]
Reimplementation of the blast settings

**Comment by culpinnis** [comment]
Added to #26 because BLAST annotation will be moved to the postprocessing

**Comment by culpinnis** [comment]
In https://github.com/tschmutzer/kmasker/commit/32d2324ed1e39df889f4efaa66a213627c3fc4b8 : any necessary settings can be adjusted by adding them to HASH_info and modifying the BLAST command line. 
We just need to know which parameters should be changeable.

**Comment by tschmutzer** [comment]
The HASH_info now has the following entries: $HASH_info{"user setting blast"}, $HASH_info{"user setting jelly"} and $HASH_info{"user setting kmasker"} for passing user settings.
Each entry has the structure of parameter (PAR) and value (VAL) with delimiter '; ': PAR1 VAL1; PAR2 VAL2; ...
Please add leading '--' to the parameter names.

**Comment by culpinnis** [comment]
Implemented with https://github.com/tschmutzer/kmasker/commit/99aa207ba9cc95d09b56421390148e4164c18396 . Needs testing.
