### ISSUE TITLE
Global repositories are empty

### ISSUE THREAD

**Issue by culpinnis** [tschmutzer/kmasker#29]
On my test machines the kindicies in the global repository are not found by kmasker (after moving them to the particular directories). The user repository is working fine. 
Can we check this again?

**Comment by tschmutzer** [comment]
Several reason for empty global repository. First, 'global repository' now is 'external repository'. Please check if external path points to the right directory (use 'Kmasker --show_path'). Second, naming patterns of k-mer indices changed. The used k-mer size is not encoded anymore in the index name. Old pre-caculated indix has to be renamed.
