### ISSUE TITLE
Nice textual output of KMASKER

### ISSUE THREAD

**Issue by culpinnis** [tschmutzer/kmasker#31]
Sometimes the textual output of KMASKER is a bit...well unsorted. 
We should suppress or rewrite some (debug) messages for the final version.
This mainly affects functions in filehandler.pm and run.pm

**Comment by culpinnis** [comment]
Improved in https://github.com/tschmutzer/kmasker/commit/f7dc7c18d4fe03def4951e1fc2496ea7d9cb7d30 (output of external scripts is written into a log file for explore and run module)

**Comment by tschmutzer** [comment]
PLOT (--histm and --hist). Add information for user to provide list of Ids and notify when plotting is not accapted.
