### ISSUE TITLE
R Paket Installation Problem

### ISSUE THREAD

**Issue by tschmutzer** [tschmutzer/kmasker#44]
Running occVisualizer.R failed:

Loading required package: pacman
Installing package into ‘/opt/Bio/R_LIBS/3.3.2’
(as ‘lib’ is unspecified)
Error in install.packages(pkgs = doing, lib = lib, ...) :
  unable to install packages
Calls: <Anonymous> ... <Anonymous> -> suppressMessages -> withCallingHandlers
Execution halted

**Comment by culpinnis** [comment]
Please try  `install.packages(c("pacman", "zoo", "getopt", "pillar", "ggplot2", "scales", "stringr"))` in an interactive R session and copy the output.

**Comment by culpinnis** [comment]
Please try with the change of commit 1e42738
