### ISSUE TITLE
Improve style of output file names

### ISSUE THREAD

**Issue by tschmutzer** [tschmutzer/kmasker#52]
Produced output file somehow lack clarity what they contain. Should be more constistent. We might rename them at the end.

**Comment by culpinnis** [comment]
Run and explore modules:
Leave the names as they are, but symlink the files to a result folder. Will be implemented!

**Comment by tschmutzer** [comment]
Agree: Symlinks will be cretated in /results
User will find all relevant output data in that directory.

Step 1: List all file names that are generated
Step 2: Decide which ones are important
Step 3: Find proper name

**Comment by culpinnis** [comment]
Kmasker run (single kindex):
`KMASKER_extracted_regions_KMASKER_kindexname....` -> Sequences without repeats
`KMASKER_kindexname....` -> Sequence with masked repeats (cmasker, no KRC - raw!)
`report_overview` -> Overview statistics made out of the following two files:
`report_statistics_KRC_RESULT....` -> KRC statistics (GFF)
`report_statistics_sequence_RESULT....` -> Sequence statistics (GFF)
`RESULT_....gff` -> GFF file with KRR/KRC
`UC_inputfilename.fa` -> Inputfile converted to uppercase

**temp**
`KMASKER_kindexname_NORM_....occ `-> OCC file (normalized) _remove from temp?_
`KMASKER_kindexname_....occ` -> OCC file (raw)
`KMASKER_kindexname...tab` -> Tab file with repeat regions
`KMASKER_kindexname..Regions_merged_.tab` -> Tab file with merged KRC
`UC_inputfile.fa.length` -> Length of the input sequences

**Comment by culpinnis** [comment]
Kmasker run (compare):
`report_statistics_sequence_RESULT....` -> Sequence statistics (GFF)
`KMASKER_comparative_FCXX_KMASKER_kindexname1....gff` -> GFF file with signigicant regions kindex1
`KMASKER_comparative_FCXX_KMASKER_kindexname2....gff` -> GFF file with signigicant regions kindex2
`KMASKER_comparative_descriptives_FCX_...stats`-> Statistics
`KMASKER_kindexname1_NORM...occ`-> OCC file (normalized)
`KMASKER_kindexname2_NORM...occ`-> OCC file (normalized)
`KMASKER_kindexname1_....occ` -> OCC file (raw)
`KMASKER_kindexname2_....occ` -> OCC file (raw)
`UC_inputfilename.fa` -> Inputfile converted to uppercase

**temp**
`KMASKER_comparative_kindexname1...tab` -> Tab file with significant regions
`KMASKER_comparative_kindexname2...tab` -> Tab file with significant regions
`KMASKER_comparative_FCXX_KMASKER_kindexname1....gff` -> GFF file with signigicant regions kindex1
`KMASKER_comparative_FCXX_KMASKER_kindexname2....gff` -> GFF file with signigicant regions kindex2
`UC_inputfile.fa.length` -> Length of the input sequences

**Comment by tschmutzer** [comment]
New naming schema compiled inkluding table which data is produced in which Kmasker calls.

**Comment by culpinnis** [comment]
Implementation of KMASKER_00_README_PID.txt tomorrow + testing.

**Comment by culpinnis** [comment]
Readme implemented & Single Kindex already tested.

**Comment by culpinnis** [comment]
https://github.com/tschmutzer/kmasker/commit/212353751ea751045b138c8d4a43644dfdc48190

**Comment by culpinnis** [comment]
KRR AND KRC are replaced in COMPARE mode with KDR AND KDC (kmer diversification cluster/region)

**Comment by culpinnis** [comment]
Everything with exception of krispr was tested. The usage of the plot comparative plot functions in EXPLORE are a bit strange but should work.

**Comment by culpinnis** [comment]
New scheming in https://github.com/tschmutzer/kmasker/releases/tag/master-190218 included.
Please re-open this issue if sth. with the naming scheme should be changed or is not working as expected.
